# NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

arr = np.array(my_list)

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(4,4)

array([[0.78265729, 0.92285245, 0.91533141, 0.69146198],
       [0.70231016, 0.51209976, 0.77168765, 0.55255729],
       [0.28979331, 0.30892554, 0.60212471, 0.22011844],
       [0.62818827, 0.14318726, 0.06803203, 0.35147609]])

In [9]:
np.random.randn(2,2)

array([[ 0.01266483, -0.3498915 ],
       [ 1.32115547,  0.03993998]])

In [10]:
np.random.randint(1,100,(4,4))

array([[79, 19, 74, 62],
       [33, 57, 96, 58],
       [66, 37, 56, 23],
       [93, 97,  7, 83]])

In [11]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 8,  7, 12, 24,  2, 43, 43,  8, 44, 18])

In [12]:
arr = np.arange(25)

arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [13]:
ranarr.max()
ranarr.argmax()

8

In [14]:

ranarr.min()

ranarr.argmin()

4

In [15]:
ranarr.dtype

dtype('int64')