# NumPy Indexing and Selection

In [62]:
import numpy as np

In [63]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[3:6]

array([3, 4, 5])

In [65]:

arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [66]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [67]:
arr [:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
slice_of_arr = arr[6:10]
slice_of_arr

array([6, 7, 8, 9])

In [69]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99])

In [70]:
arr

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  10])

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d[2,2]
arr_2d[2][2]

45

In [72]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[arr > 5]
arr[arr <= 3]

array([1, 2, 3])

In [77]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr_2d[2:,:9]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45, 46, 47, 48]])