# NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]

arr = np.array(my_list)

In [ ]:
np.zeros((5,5))

In [ ]:
np.arange(0,11,2)

In [ ]:
np.ones((8,8))

In [ ]:
np.linspace(0,10,100)

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.random.rand(4,4)

array([[0.97978784, 0.28823627, 0.4305307 , 0.81390989],
       [0.79448547, 0.06568206, 0.01014425, 0.54618661],
       [0.73193057, 0.8713928 , 0.93895491, 0.04391833],
       [0.13019229, 0.59866698, 0.8468199 , 0.29891762]])

In [53]:
np.random.randn(2,2)

array([[-0.55587137, -1.29112499],
       [ 0.87672055,  0.96653885]])

In [55]:
np.random.randint(1,100,(4,4))

array([[60, 99, 33, 28],
       [44, 15, 33, 27],
       [72,  3,  1, 30],
       [65, 72, 16, 76]])

In [89]:
ranarr = np.random.randint(0,50,10)
ranarr

array([31, 34, 44, 48, 14, 38, 28, 29, 33, 19])

In [99]:
arr = np.arange(25)

arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [100]:
ranarr.max()
ranarr.argmax()

3

In [101]:

ranarr.min()

ranarr.argmin()

4

In [103]:
ranarr.dtype

dtype('int64')